---
- name: Copy files/folder to remote machines
  hosts: TR1 TR2
  gather_facts: no
  tasks:
   - copy: 
       src: "/media/penelopeprime/EMBO_Metabolomics/Day 3/Networks_Jourdan/MetaNetter.jar"
       dest: /usr/local/Cytoscape_v2.8.3/plugins/ 
       owner: root 
       mode: 0777
    
   - copy: 
       src: "/media/penelopeprime/EMBO_Metabolomics/Day 3/Networks_Jourdan" 
       dest: /home/training/ 
       owner: training 
       mode: 0777

   - shell: chmod 777 -R /home/training/Networks_Jourdan
