---
- name: Copy files/folder to remote machines
  hosts: TR2
  gather_facts: no
  tasks:
#   - copy: 
#       src: "/media/penelopeprime/Gene_fusion"
#       dest: /home/training/
#       remote_src: True 
#       owner: training 
#       mode: 0777
    
   - copy: 
       src: "/media/penelopeprime/Archive/pythonrc-minimal" 
       dest: /home/training/.pythonrc-minimal
#       remote_src: True
       owner: training
       mode: 0777

#   - shell: chmod 777 -R /home/training/Gene_fusion
   - shell: chmod 777 -R /home/training/.pythonrc-minimal
