- name: run command on terminal
  gather_facts: no
  hosts: TR1
  tasks:
#   - apt:
#      name: python-pip
#      update_cache: yes

#   - raw: pip install --upgrade pip

   - pip: name=pip state=latest
   - pip: name=limix
