---
- name: Restart hosts
  gather_facts: no
  hosts: ImmunoVM-33
  tasks:
   - apt: pkg=nvidia-375 state=absent
   - apt: pkg=nvidia-340 state=installed update_cache=true

   - name: restart machine
     command: shutdown -r now "Ansible reboot triggred"
     async: 0
     poll: 0
     ignore_errors: true
