---
- name: Windows Power Control
  hosts: ThinClientTR2 ThinClient ThinClientTR1
#ThinClientTR1 ThinClientTR2
  gather_facts: no
  tasks:
    - name: Restart all Machines  
      win_reboot:
        msg: Reboot initiated by Ansible
