---
- name : Execute Windows Update 
  hosts: r1u29
#ThinClientTR1 ThinClientTR2
  gather_facts: no
  tasks:
    - name: make sure that the  Windows update service is running
      win_service:
        name: wuauserv
        start_mode: delayed
        state: started
      ignore_errors: yes

    - name: Executing Windows Update 
      win_updates: 
        category_names: 
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - DefinitionUpdates
          - FeaturePacks
#          - Application
          - ServicePacks
#          - Tools
          - Updates
        state: installed
      ignore_errors: yes
      register: update_result

    - win_reboot:
      when: update_result.reboot_required

#    - debug: var=update_result.updates.title
#    - debug: var=update_result.updates.installed
#    - debug: var=update_result.installed_update_count
    - debug: var=update_result.failed_update_count   
